name: Hello
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: clone repo
              run: actions/checkout@v3
                #   |
                #   echo  "cloning repo "
                #   echo  "echo ${{toJson(github)}}"
                #   git clone https://github.com/${{github.repository}}.git myFiles
                #   cd && ls myFiles rr
            - name: Setup node js
              uses: actions/setup-node@v4
              with:
                node_version: 22
            - name: print node version
              run: node -v
            - name: Install dependecies
              run: npm install
            - name: Run tests
              run: npm run test
            - name: Completed job
              run: echo "Completed job"

